---
title: "Untitled"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# install.packages("gapminder")
# install.packages("wesanderson")
# install.packages("ggthemes")

library(tidyverse)
library(gapminder)
library(wesanderson)
library(ggthemes)

```
# Basic Plots
```{r}
head(gapminder)
gap07 <- filter(gapminder, year == 2007)

gap07_median <-  gap07 %>% 
  group_by(continent) %>% summarize(med=median(pop))

gap07_median %>% ggplot(aes(x=continent,y=med)) +
  geom_bar(stat="identity")          

gap_iceland <- gapminder %>% filter(country == "Iceland") 
head(gap_iceland)

p <- gap_iceland %>% ggplot(aes(x=year,y=gdpPercap))
#opt 1
p + geom_point()  +
    geom_line() + 
    ggsave("iceland.png", height = 6, width = 8)
#opt 2
p + geom_point()  +
    geom_line() 
p + ggsave("iceland2.png", height = 6, width = 8)

```

# Viewing data distributions
```{r}
# 1
gap07 %>% ggplot(aes(gdpPercap)) + geom_histogram()

gap07 %>% ggplot(aes(gdpPercap)) + 
  geom_histogram(bins = 15)

gap07 %>% ggplot(aes(gdpPercap)) + geom_histogram(binwidth=5000)

gap07 %>% ggplot(aes(gdpPercap)) + geom_density()

# 2 
gap07 %>% ggplot(aes(continent, lifeExp)) + geom_boxplot()

gap07 %>% ggplot(aes(continent, lifeExp)) + 
  geom_boxplot() +
  geom_jitter()

gap07 %>% ggplot(aes(continent, lifeExp)) + 
  geom_boxplot() +
  geom_jitter(width = 0.5, alpha = 0.2)

```
# Additional Encodings
```{r}
gap07 %>% ggplot(aes(gdpPercap, lifeExp, size=pop, color=continent)) + 
  geom_point()

gap_pop <- gapminder %>% group_by(continent,year) %>% summarize(meanpop = mean(pop))
gap_pop %>% ggplot(aes(year,meanpop)) +
  geom_line()
gap_pop %>% ggplot(aes(year,meanpop, group=continent)) +
  geom_line()
gap_pop %>% ggplot(aes(year,meanpop, color=continent)) +
  geom_line()

```
# Small Multiples
```{r}
gapminder %>% ggplot(aes(gdpPercap, lifeExp)) + 
  geom_point() +
  facet_grid((continent ~ year))

gap_life <- gapminder %>% group_by(continent,year) %>% 
  summarize(meanlifeExp = mean(lifeExp))

gap_life %>% ggplot(aes(year,meanlifeExp)) +
  geom_line() +
  facet_grid(continent ~ .)

gap_life %>% ggplot(aes(year,meanlifeExp)) +
  geom_line() +
  facet_grid(. ~ continent)

gap_life %>% ggplot(aes(year,meanlifeExp)) +
  geom_line() +
  facet_wrap(~continent)
```
# Smoothing Functions
```{r}
gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  geom_smooth(span=0.2)

gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  geom_smooth(span=0.9)

gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  geom_smooth(se=FALSE)

gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  geom_smooth(level=0.90)

gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  geom_smooth(method=lm)

gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  geom_smooth(span=0.2)

gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~continent)

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~continent)

gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  geom_smooth(aes(color=continent)) +
  facet_wrap(~continent)
```

# Axis Scales
```{r}
gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  scale_x_continuous()

gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  scale_x_continuous(trans = "log10")

gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  scale_x_log10()

gap07 %>% ggplot(aes(gdpPercap,lifeExp)) +
  geom_point() +
  scale_x_log10() +
  scale_y_continuous(limits = c(0,90))

```

# Alternate Color Scales
```{r}
gap07 %>% ggplot(aes(gdpPercap, lifeExp, color = continent)) + 
  geom_point() +
  scale_x_log10()

gap07 %>% ggplot(aes(gdpPercap, lifeExp, color = continent)) + 
  geom_point() +
  scale_x_log10() +
  scale_color_brewer(palette = "Dark2")

gap07 %>% ggplot(aes(gdpPercap, lifeExp, color = continent)) + 
  geom_point() +
  scale_x_log10() +
  scale_color_manual(values = wes_palette("Darjeeling1"))

# names(wes_palettes)
# wes_palette("Darjeeling1")

gap07 %>% ggplot(aes(gdpPercap, lifeExp)) + 
  geom_point(color="blue", size=6) +
  scale_x_log10() 
```

# Themes
```{r}
gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point() +
  geom_smooth() +
  scale_x_log10() +
  theme_gray()

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point() +
  geom_smooth() +
  scale_x_log10() +
  theme_bw()

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point() +
  geom_smooth() +
  scale_x_log10() +
  theme_dark()

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point() +
  geom_smooth() +
  scale_x_log10() +
  theme_void()

# ggtheme
gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point() +
  geom_smooth() +
  scale_x_log10() +
  theme_tufte()

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point() +
  geom_smooth() +
  scale_x_log10() +
  theme_solarized() +
  scale_colour_solarized("blue")

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point() +
  geom_smooth() +
  scale_x_log10() +
  theme_base()

```

# Customizing Titles etc.
```{r}

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point(size=2) +
  geom_smooth() +
  scale_x_log10() +
  theme_light()

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point(size=2) +
  geom_smooth() +
  scale_x_log10() +
  theme_light() +
  theme(legend.position = "bottom")

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point(size=2) +
  geom_smooth() +
  scale_x_log10() +
  theme_light() +
  theme(legend.position = "none")

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point(size=2) +
  geom_smooth() +
  scale_x_log10() +
  theme_light() +
  theme(legend.position = c(0.1, 0.85))

gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point(size=2) +
  geom_smooth() +
  scale_x_log10() +
  theme_light() +
  theme(legend.position = c(0.1, 0.85)) +
  ggsave("life_exp_gdp_2007_custom.png", 
         width = 7, height = 7)
  
gap07 %>% ggplot(aes(gdpPercap,lifeExp, color=continent)) +
  geom_point(size=2) +
  geom_smooth() +
  scale_x_log10() +
  theme_light() +
  theme(legend.position = c(0.1, 0.85),
        legend.key = element_blank(),
        axis.text = element_text(size=12),
        axis.title = element_text(size=14)) +
  labs(x="Per Capita GDP",
       y="Life Expectancy",
       title="2007 Life Expectancy and GDP",
       color="Continent") +
  ggsave("life_exp_gdp_2007_custom.png", 
         width = 7, height = 7)

```





